create table if not exists public.documentary_requests (
  id bigint generated by default as identity primary key,
  tmdb_id integer not null,
  media_type text not null default 'movie' check (media_type in ('movie','tv')),
  title text not null,
  overview text,
  runtime integer,
  rating numeric(4,2),
  poster_url text,
  requested_by text not null check (requested_by in ('Becs','Charlie','Lisa','Ashley','Krishna')),
  created_at timestamptz not null default now(),
  watched_at timestamptz
);

-- Safe to run against an existing V1 database.
alter table public.documentary_requests
  add column if not exists media_type text not null default 'movie';

alter table public.documentary_requests
  drop constraint if exists documentary_requests_media_type_check;

alter table public.documentary_requests
  add constraint documentary_requests_media_type_check check (media_type in ('movie','tv'));

drop index if exists public.one_active_request_per_documentary;

create unique index if not exists one_active_request_per_documentary
on public.documentary_requests (tmdb_id, media_type)
where watched_at is null;

alter table public.documentary_requests enable row level security;

drop policy if exists "Anyone can read documentary requests" on public.documentary_requests;
drop policy if exists "Anyone can add documentary requests" on public.documentary_requests;
drop policy if exists "Anyone can update documentary requests" on public.documentary_requests;
drop policy if exists "Anyone can delete documentary requests" on public.documentary_requests;

create policy "Anyone can read documentary requests"
on public.documentary_requests for select
to anon, authenticated
using (true);

create policy "Anyone can add documentary requests"
on public.documentary_requests for insert
to anon, authenticated
with check (
  requested_by in ('Becs','Charlie','Lisa','Ashley','Krishna')
  and media_type in ('movie','tv')
);

create policy "Anyone can update documentary requests"
on public.documentary_requests for update
to anon, authenticated
using (true)
with check (
  requested_by in ('Becs','Charlie','Lisa','Ashley','Krishna')
  and media_type in ('movie','tv')
);

create policy "Anyone can delete documentary requests"
on public.documentary_requests for delete
to anon, authenticated
using (true);
