create table if not exists public.documentary_requests (
  id bigint generated by default as identity primary key,
  tmdb_id integer not null,
  title text not null,
  overview text,
  runtime integer,
  rating numeric(4,2),
  poster_url text,
  requested_by text not null check (requested_by in ('Becs','Charlie','Lisa','Ashley','Krishna')),
  created_at timestamptz not null default now(),
  watched_at timestamptz
);

create unique index if not exists one_active_request_per_documentary
on public.documentary_requests (tmdb_id)
where watched_at is null;

alter table public.documentary_requests enable row level security;

create policy "Anyone can read documentary requests"
on public.documentary_requests for select
to anon, authenticated
using (true);

create policy "Anyone can add documentary requests"
on public.documentary_requests for insert
to anon, authenticated
with check (requested_by in ('Becs','Charlie','Lisa','Ashley','Krishna'));

create policy "Anyone can update documentary requests"
on public.documentary_requests for update
to anon, authenticated
using (true)
with check (requested_by in ('Becs','Charlie','Lisa','Ashley','Krishna'));

create policy "Anyone can delete documentary requests"
on public.documentary_requests for delete
to anon, authenticated
using (true);
